# Для локальной разработки
version: "3.9"
services:
  app:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    command: /bin/sh -c "bundle exec rake db:setup && bundle exec rake bot:run"
    env_file: .env
  database:
    image: postgres:12.1
    environment:
      POSTGRES_DB: 1000-push-ups 
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
