development:
  adapter: postgresql
  database: 1000-push-ups-dev 
  username: postgres
  password: password
  port: 5432 
  host: database 
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: 1000-push-ups-test 
  username: postgres
  password: password
  port: 5678
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: 1000-push-ups 
  username: postgres 
  password: password 
  port: 5678
  host: localhost  
  pool: 5
  timeout: 5000
